# .github/workflows/agentic-system.yml
name: Agentic System
on:
  workflow_dispatch:
    inputs:
      agent:
        type: choice
        options: [issue, coordinator, codegen, review, pr, kpi]
      issue_number:
        type: string
        required: true
      files:
        type: string
        required: false
      branch:
        type: string
        default: main

jobs:
  issue:
    if: ${{ inputs.agent == 'issue' }}
    uses: Enushin/agentic-workflows/.github/workflows/agentic-core.yml@v1.0.0
    with:
      agent: issue
      issue_number: ${{ inputs.issue_number }}
      branch: ${{ inputs.branch }}

  coordinator:
    if: ${{ inputs.agent == 'coordinator' }}
    uses: Enushin/agentic-workflows/.github/workflows/agentic-core.yml@v1.0.0
    with:
      agent: coordinator
      issue_number: ${{ inputs.issue_number }}
      branch: ${{ inputs.branch }}

  codegen:
    if: ${{ inputs.agent == 'codegen' }}
    uses: Enushin/agentic-workflows/.github/workflows/agentic-core.yml@v1.0.0
    with:
      agent: codegen
      issue_number: ${{ inputs.issue_number }}
      branch: ${{ inputs.branch }}
      files: ${{ inputs.files }}

  review:
    if: ${{ inputs.agent == 'review' }}
    uses: Enushin/agentic-workflows/.github/workflows/agentic-core.yml@v1.0.0
    with:
      agent: review
      issue_number: ${{ inputs.issue_number }}
      branch: ${{ inputs.branch }}
      files: ${{ inputs.files }}

  pr:
    if: ${{ inputs.agent == 'pr' }}
    uses: Enushin/agentic-workflows/.github/workflows/agentic-core.yml@v1.0.0
    with:
      agent: pr
      issue_number: ${{ inputs.issue_number }}
      branch: ${{ inputs.branch }}

  kpi:
    if: ${{ inputs.agent == 'kpi' }}
    uses: Enushin/agentic-workflows/.github/workflows/agentic-core.yml@v1.0.0
    with:
      agent: kpi
      issue_number: ${{ inputs.issue_number }}
      branch: ${{ inputs.branch }}
